name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies
        run: dotnet restore src/BookManagement.API/BookManagement.API.csproj

      - name: Build Application
        run: dotnet build src/BookManagement.API/BookManagement.API.csproj --configuration Release --no-restore

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore Test Dependencies
        run: dotnet restore src/BookManagement.Tests/BookManagement.Tests.csproj

      - name: Run Unit Tests
        run: dotnet test src/BookManagement.Tests/BookManagement.Tests.csproj --no-restore --verbosity quiet
